version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api" 
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/client" 
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
