version: "3.12"

services:

  frontend:
    image: index-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    image: index-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:80"