version: "3.12"

services:
  frontend:
    image: index-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    image: index-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:80"
    depends_on:
      - weaviate
      - ollama

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: 'var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama'
      CLUSTER_HOSTNAME: 'node1'

  ollama:
    image: ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"

volumes:

  weaviate_data:
    driver: local