# Define the base image
FROM python:3.11

ENV WEAVIATE_URL=http://ww8.index.k8s.bio.scai.fraunhofer.de

COPY routes.py .

# Install API requirements
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt

EXPOSE 80

# API entry point
CMD ["uvicorn", "routes:app", "--host", "0.0.0.0", "--port", "80"]
