# Define the base image
FROM python:3.11

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt

RUN pip install -r /api/requirements.txt

COPY ./app /api/app

EXPOSE 80

# API entry point
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
