# Define the base image
FROM python:3.11

ENV WEAVIATE_URL=http://ww8.index.k8s.bio.scai.fraunhofer.de
ENV OLLAMA_URL=http://nomic-embed-text.ollama.k8s.bio.scai.fraunhofer.de

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt

RUN pip install -r /api/requirements.txt

COPY ./app /api/app

EXPOSE 80

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
