name: Docker publish

on:
  release:
    types: [published]

jobs:

  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Version Tag
      id: version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> "$GITHUB_OUTPUT"
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & push api
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./api/Dockerfile
        push: true
        tags: |
          ghcr.io/scai-bio/index/api:latest
          ghcr.io/scai-bio/index/api:${{ steps.version.outputs.VERSION }}
    - name: Build & push client
      uses: docker/build-push-action@v2
      with:
        context: ./client
        file: ./client/Dockerfile.prod
        push: true
        tags: |
          ghcr.io/scai-bio/index/api:latest
          ghcr.io/scai-bio/index/api:${{ steps.version.outputs.VERSION }}
